### ISSUE TITLE
SchemaTypeCoder should handle "additionalProperties"

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#112]
Given the following schema:

```yaml
type: object
  additionalProperties:
    type: integer
```

SchemaTypeCoder should yield the following type:

```ts
{
    [k: string]: number
}
```

However, given the following schema.

```yaml
type: object
  properties:
    name: firstName
    type: string 
  additionalProperties:
    type: integer
```

All properties _except_ name should be numbers. [TypeScript currently has no way to represent an object with some properties that have one type and all other properties of another type.](
https://github.com/microsoft/TypeScript/issues/17867) The best we can do is this:

```ts
{
    name?: string
    [k: string]: unknown
}
```

It also needs to handle the case where `additionalProperties` is `true` or `false`.

Now that I've written it out I realize it boils down to something like this.

```js

if (hasAdditionalProperties) {
    if(hasProperties) {
       append('[k: string]: unknown')
    } else {
       append(`[k: string]: ${additionalProperties.type}`)
    } 
}
```

I don't really care about this case at this point, but if ALL of the properties happen to have the same type as `additionalProperties`, then we can resolve the type instead of putting `unknown` in.
